[project]
name = "usage"
version = "0.1.0"
requires-python = "==3.10.*" # The oldest version supported by Solie
dependencies = ["solie"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
