"""Constants used throughout the application."""

# HTTP Status Codes
HTTP_OK = 200

# Time Constants (in seconds)
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86400
SECONDS_PER_MONTH = 2678400  # 31 days
SECONDS_PER_YEAR = 31622400  # 366 days
TWENTY_SECONDS = 20
TWO_SECONDS = 2
TWO_MINUTES = 120
TWENTY_MINUTES = 1200

# UI Constraints
MAX_SELECTED_COINS = 12
MIN_SELECTED_COINS = 1
LONG_SYMBOL_LIST_THRESHOLD = 5
MAX_TICK_LABELS = 12

# Progress Bar
PROGRESS_BAR_MAX = 1000

# Calculation/Simulation
MAX_PREPARATION_STEPS = 6
MIN_PEAK_COUNT = 12

# Data Collection
MAX_REQUEST_RETRIES = 10
MIN_SERVER_TIME_SAMPLES = 30

# Decision Constants
COLUMN_PARTS_COUNT = 3

# Magic Number Replacements
MIN_SERIES_LENGTH = 2
EXIT_DIALOG_ANSWER = 2
