[project]
name = "solie-runner"
version = "0.1.0"
requires-python = "==3.10.*"                                # The oldest version supported
dependencies = ["solie", "pyright~=1.1.392", "ruff~=0.9.3"]
