site_name: Solie Docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Noto Sans
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      scheme: default
      toggle:
        icon: material/brightness-7
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.footer

plugins:
  - search
  - awesome-pages
  - glightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
